# This file is part of core-net Rust crate containing useful reusable
# networking utilities.
#
# Copyright (C) 2026 to present, Duncan Crutchley
# Contact <15799155+dac1976@users.noreply.github.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License and GNU Lesser General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# and GNU Lesser General Public License along with this program. If
# not, see <http://www.gnu.org/licenses/>.

[package]
name = "core_net"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
thiserror = "2"
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "registry"] }
socket2 = "0.6"
miette = { version = "7", features = ["fancy"] }
time = { version = "0.3", features = ["formatting", "local-offset", "macros"] }
tracing-rolling-file = "0.1"
serde = { version = "1", features = ["derive"] }
rmp-serde = "1"
windows-sys = { version = "0.61", features = ["Win32_Networking_WinSock"] }
winapi = { version = "0.3", features = ["winsock2", "ws2ipdef", "mstcpip"] }

[dev-dependencies]