// This file is part of core-net Rust crate containing useful reusable
// networking utilities.
//
// Copyright (C) 2026 to present, Duncan Crutchley
// Contact <15799155+dac1976@users.noreply.github.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License and GNU Lesser General Public License
// for more details.
//
// You should have received a copy of the GNU General Public License
// and GNU Lesser General Public License along with this program. If
// not, see <http://www.gnu.org/licenses/>.

/// Demo application handlers.
///
/// Contains example request/reply handlers demonstrating:
///
/// - raw messages
/// - echo handling
/// - deferred/background work
/// - MessagePack payloads
mod app;

use app::handlers;

use core_net::{
    config::{KeepAliveOption, SendOption, TcpServerConfig},
    logging::{LogTimeMode, LoggingConfig, init_tracing},
    messaging::dispatcher::{MessageContext, MessageDispatcherBuilder, ReplyHandle},
    messaging::message::Message,
    protocol::DEFAULT_MAGIC_STRING,
    tcp_server::{AppEvent, TcpServer},
};

use miette::{IntoDiagnostic, Result, WrapErr};

use tokio::sync::mpsc;

use tracing::{error, info};

/// Demo TCP server entry point.
///
/// This application demonstrates:
///
/// - core_net TCP server usage
/// - dispatcher-based message routing
/// - async request/reply handling
/// - structured tracing/logging
/// - pooled message buffers
/// - MessagePack integration
///
/// High-level architecture:
///
/// ```text
/// TCP socket
///   -> TcpServer
///   -> AppEvent::MessageReceived
///   -> MessageDispatcher
///   -> registered async handlers
/// ```
#[tokio::main]
async fn main() -> Result<()> {
    // Initialise structured tracing/logging.
    //
    // Logs are written both:
    //
    // - to rotating log files
    // - to stderr/console
    init_tracing(&LoggingConfig {
        directory: "logs",
        file_name: "demo_server.log",
        max_bytes: 5 * 1024 * 1024,
        keep_files: 10,
        level_filter: "info",
        time_mode: LogTimeMode::Utc,
        also_stderr: true,
    })
    .wrap_err("failed to initialize tracing")?;

    // Application event channel.
    //
    // TcpServer publishes connection/message lifecycle events here.
    let (tx, mut rx) = mpsc::channel(1024);

    // Configure TCP server and core_net runtime behaviour.
    let mut cfg = TcpServerConfig::default();

    // Disable Nagle to reduce latency for small request/reply messages.
    cfg.socket.send_option = SendOption::NagleOff;

    // Enable TCP keepalive support.
    cfg.socket.keep_alive = KeepAliveOption::On;

    // Increase OS socket buffer sizes.
    //
    // Useful for higher-throughput testing and reducing kernel-level
    // backpressure.
    cfg.socket.send_buffer_size = Some(256 * 1024);
    cfg.socket.recv_buffer_size = Some(256 * 1024);

    // Size of pooled outbound message buffers.
    cfg.send_pool_msg_size = 8192;

    // Receive message pool configuration.
    //
    // Incoming messages are stored in reusable pooled buffers to minimise
    // allocation churn.
    cfg.recv_pool_msg_count = 128;
    cfg.recv_pool_msg_size = 8192;

    // TCP receive chunk size.
    //
    // Controls how much data is read from the socket per async receive
    // operation.
    cfg.recv_chunk_size = 64 * 1024;

    // Expected protocol magic string.
    //
    // Incoming messages with the wrong protocol magic are rejected by the
    // core_net parsing layer.
    cfg.expected_magic_string = DEFAULT_MAGIC_STRING;

    // Create dispatcher builder.
    //
    // Handlers are registered by message id.
    let mut dispatcher_builder = MessageDispatcherBuilder::new();

    // Register demo handlers.
    handlers::register_handlers(&mut dispatcher_builder);

    // Finalise dispatcher.
    let dispatcher = dispatcher_builder.build();

    // Bind TCP server socket.
    let server = TcpServer::bind("127.0.0.1:9000".parse().into_diagnostic()?, cfg.clone(), tx)
        .await
        .into_diagnostic()
        .wrap_err("failed to bind TCP server")?;

    // Handle used for:
    //
    // - replies
    // - disconnect requests
    // - external server interaction
    let handle = server.handle();

    // Run TCP server in background task.
    tokio::spawn(async move {
        if let Err(err) = server.run().await {
            error!(error = %err, "server failed");
        }
    });

    info!("demo server listening on 127.0.0.1:9000");

    // Main application event loop.
    //
    // Receives events generated by TcpServer.
    while let Some(event) = rx.recv().await {
        match event {
            // New client connected.
            AppEvent::ClientConnected {
                client_id,
                peer_addr,
            } => {
                info!(client_id, %peer_addr, "client connected");
            }

            // Existing client disconnected.
            AppEvent::ClientDisconnected {
                client_id,
                peer_addr,
            } => {
                info!(client_id, %peer_addr, "client disconnected");
            }

            // Message received from client.
            AppEvent::MessageReceived {
                client_id,
                peer_addr,
                message,
            } => {
                // Convert low-level TCP server message into generic dispatcher
                // message type.
                //
                // This provides a transport-independent abstraction layer
                // above the TCP transport.
                let app_message = Message::from_tcp_server(peer_addr, message);

                // Build dispatcher context.
                //
                // MessageContext carries:
                //
                // - source metadata
                // - reply routing
                // - protocol configuration
                //
                // into the async handler layer.
                let ctx = MessageContext {
                    source_addr: Some(peer_addr),

                    expected_magic: cfg.expected_magic_string,

                    reply_handle: ReplyHandle::TcpServer {
                        client_id,

                        handle: handle.clone(),
                    },
                };

                // Dispatch message to the registered async handler based on
                // message id.
                dispatcher.dispatch(ctx, app_message).await;
            }
        }
    }

    Ok(())
}
